dist: trusty
sudo: false

language: python

env:
  - DISPLAY=:99 PATH=/usr/lib/chromium-browser:$PATH

addons:
  apt:
    packages:
      - build-essential
      - chromium-chromedriver
      - curl
      - git
      - libffi-dev
      - uuid-dev
      - wget
      - graphviz

matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: osx
      language: generic

install:
  - ./.travis/setup.sh

script:
  - ./.travis/test.sh
