name: Build and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.cp }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            python: '3.12'
            cp: '312'
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

            # MacOS x86_64
          - os: macos-latest-large
            python: '3.12'
            cp: '312'
            platform_id: macosx_x86_64

    steps:
      - name: Checkout TextWorld
        uses: actions/checkout@v5

      - name: Build Wheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp${{ matrix.cp }}-${{ matrix.platform_id }}
          CIBW_ARCHS: native  # avoid building extra archs unintentionally
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: wheelhouse

      - name: Retag wheels to py3-none-<platform>
        run: python tools/retag_wheel_py3-none.py wheelhouse

      - name: Install dependencies (Linux)
        run: sudo apt update && sudo apt install -y --no-install-recommends graphviz
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install dependencies (MacOS)
        run: brew install graphviz
        if: startsWith(matrix.os, 'macos')

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install TextWorld from the wheel
        run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install `ls wheelhouse/*.whl`[dev]

      - name: Run tests
        run: |
          pytest -n 16 -sv tests/ textworld/

      - uses: actions/upload-artifact@v4
        with:
          name: tw-wheels-py3-none-${{ matrix.platform_id }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install build
      - name: Build package
        run: python -m build --sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tw-sdist
          path: dist/*.tar.gz
          if-no-files-found: error

  upload_pypi:
    name: >-
        Publish TextWorld ðŸ“¦ to PyPI
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/textworld/
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: tw-*
          path: dist
          merge-multiple: true
      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
