name: "Run tests and coverage"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest-large, macos-latest]
        python: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v5
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies (Linux)
        run: sudo apt update && sudo apt install -y --no-install-recommends graphviz
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install dependencies (MacOS)
        run: brew install graphviz
        if: startsWith(matrix.os, 'macos')

      - name: Install TextWorld from source
        run: |
            python -m pip install --upgrade pip
            pip install -e .[dev]
      - name: Run tests
        run: |
            pytest -n 16 -sv --cov=textworld --cov-report=term-missing --cov-fail-under=85 tests/ textworld/
