name: "Test from PyPi"

on:
  workflow_run:
    workflows: ["Build and upload to PyPI"]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest-large, macos-latest]
        python: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies (Linux)
        run: sudo apt update && sudo apt install -y --no-install-recommends graphviz
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install dependencies (MacOS)
        run: brew install graphviz
        if: startsWith(matrix.os, 'macos')

      - name: Install TextWorld
        run: |
            python -m pip install --upgrade pip
            pip install textworld[dev]
      - name: Run tests
        run: |
            pytest -n 1 -sv tests/ textworld/
